### ISSUE TITLE
push update to firefox store

### ISSUE THREAD

**Issue by Carrybag1** [FrancoisMentec/PoE-Trade-Extension#12]
Hey

Can you push the update to the firefox store aswell?

**Comment by FrancoisMentec** [comment]
I lost access to my Firefox account, it's asking for an auth app I doesn't know about, and doesn't send the email to recover my account. It really pissed me and since there is 15 times less people on Firefox than Chrome using my extension I didn't bother too much.

I'll try to look more into it next week (I'm off for the WE). In the meantime you can manually install the extension by following the instructions in the README.

**Comment by FrancoisMentec** [comment]
Done, enjoy 😉
