### ISSUE TITLE
pob.party error, cant import build

### ISSUE THREAD

**Issue by BlazetalonBF** [FrancoisMentec/PoE-Trade-Extension#7]
![image](https://user-images.githubusercontent.com/78149874/106134946-8a045e80-6167-11eb-8593-26ad92e1ad93.png)

**Comment by FrancoisMentec** [comment]
Yes, I know about this error, got the same on chrome, firefox and edge. My extension, unfortunately, need pob.party to work so I can't do anything. I've tried in the past to contact pob.party creator and to port pob to the web myself, but I've failed at both. We can just wait and hope for an update to pob.party.

**Comment by BlazetalonBF** [comment]
alright cool thx alot

**Comment by Vital1984** [comment]
can this tool not direct import from path of building ? pob.party dont work

**Comment by FrancoisMentec** [comment]
No, it can't, a browser extension has a lot of restrictions, I can't execute or communicate with a desktop program like PoB. I'm using pob.party because I failed at porting PoB to the web myself. Another alternative would be to make my own web browser but it's too much work, it would require building on top of chromium if I want other trade extensions to work with it too. I'll try again to compile PoB to webassembly this WE, but I don't have too much hope.

**Comment by Barragek0** [comment]
> 
> 
> No, it can't, a browser extension has a lot of restrictions, I can't execute or communicate with a desktop program like PoB. I'm using pob.party because I failed at porting PoB to the web myself. Another alternative would be to make my own web browser but it's too much work, it would require building on top of chromium if I want other trade extensions to work with it too. I'll try again to compile PoB to webassembly this WE, but I don't have too much hope.

Could maybe use poeplanner instead?

**Comment by FrancoisMentec** [comment]
I don' think PoE Planner computes DPS and other stats. Can't find it.

**Comment by FrancoisMentec** [comment]
pob.party has been updated and work again, so does this extension.
